//
// This file was automatically generated and should not be edited.
//
//  JKHiOSDevice.h
//  Orchard
//
//  Created by Jeff Kelley on 7/17/18.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, JKHiOSDevice) {

    // iPhones
    JKHiOSDeviceiPhone NS_ENUM_DEPRECATED_IOS(1.0, 3.2) NS_SWIFT_NAME(iPhone),
    JKHiOSDeviceiPhone3G NS_ENUM_DEPRECATED_IOS(2.0, 4.3) NS_SWIFT_NAME(iPhone3G),
    JKHiOSDeviceiPhone3GS NS_ENUM_DEPRECATED_IOS(3.0, 7.0) NS_SWIFT_NAME(iPhone3GS),
    JKHiOSDeviceiPhone4 NS_ENUM_DEPRECATED_IOS(4.0, 8.0) NS_SWIFT_NAME(iPhone4),
    JKHiOSDeviceiPhone4S NS_ENUM_DEPRECATED_IOS(5.0, 10.0) NS_SWIFT_NAME(iPhone4S),
    JKHiOSDeviceiPhone5 NS_ENUM_DEPRECATED_IOS(6.0, 11.0) NS_SWIFT_NAME(iPhone5),
    JKHiOSDeviceiPhone5c NS_ENUM_DEPRECATED_IOS(7.0, 11.0) NS_SWIFT_NAME(iPhone5c),
    JKHiOSDeviceiPhone5s NS_ENUM_AVAILABLE_IOS(7.0) NS_SWIFT_NAME(iPhone5s),
    JKHiOSDeviceiPhone6 NS_ENUM_AVAILABLE_IOS(8.0) NS_SWIFT_NAME(iPhone6),
    JKHiOSDeviceiPhone6Plus NS_ENUM_AVAILABLE_IOS(8.0) NS_SWIFT_NAME(iPhone6Plus),
    JKHiOSDeviceiPhone6s NS_ENUM_AVAILABLE_IOS(9.0) NS_SWIFT_NAME(iPhone6s),
    JKHiOSDeviceiPhone6sPlus NS_ENUM_AVAILABLE_IOS(9.0) NS_SWIFT_NAME(iPhone6sPlus),
    JKHiOSDeviceiPhoneSE NS_ENUM_AVAILABLE_IOS(9.3) NS_SWIFT_NAME(iPhoneSE),
    JKHiOSDeviceiPhone7 NS_ENUM_AVAILABLE_IOS(10.0) NS_SWIFT_NAME(iPhone7),
    JKHiOSDeviceiPhone7Plus NS_ENUM_AVAILABLE_IOS(10.0) NS_SWIFT_NAME(iPhone7Plus),
    JKHiOSDeviceiPhone8 NS_ENUM_AVAILABLE_IOS(11.0) NS_SWIFT_NAME(iPhone8),
    JKHiOSDeviceiPhone8Plus NS_ENUM_AVAILABLE_IOS(11.0) NS_SWIFT_NAME(iPhone8Plus),
    JKHiOSDeviceiPhoneX NS_ENUM_AVAILABLE_IOS(11.0) NS_SWIFT_NAME(iPhoneX),

    // iPads
    JKHiOSDeviceiPad NS_ENUM_DEPRECATED_IOS(3.2, 6.0) NS_SWIFT_NAME(iPad),
    JKHiOSDeviceiPad2 NS_ENUM_DEPRECATED_IOS(4.3, 10.0) NS_SWIFT_NAME(iPad2),
    JKHiOSDeviceiPad3 NS_ENUM_DEPRECATED_IOS(5.1, 10.0) NS_SWIFT_NAME(iPad3),
    JKHiOSDeviceiPad4 NS_ENUM_DEPRECATED_IOS(6.0, 11.0) NS_SWIFT_NAME(iPad4),
    JKHiOSDeviceiPadMini NS_ENUM_DEPRECATED_IOS(3.0, 10.0) NS_SWIFT_NAME(iPadMini),
    JKHiOSDeviceiPadAir NS_ENUM_AVAILABLE_IOS(7.0) NS_SWIFT_NAME(iPadAir),
    JKHiOSDeviceiPadMini2 NS_ENUM_AVAILABLE_IOS(7.0) NS_SWIFT_NAME(iPadMini2),
    JKHiOSDeviceiPadAir2 NS_ENUM_AVAILABLE_IOS(8.1) NS_SWIFT_NAME(iPadAir2),
    JKHiOSDeviceiPadMini3 NS_ENUM_AVAILABLE_IOS(8.1) NS_SWIFT_NAME(iPadMini3),
    JKHiOSDeviceiPadMini4 NS_ENUM_AVAILABLE_IOS(9.0) NS_SWIFT_NAME(iPadMini4),
    JKHiOSDeviceiPadPro12_9Inch NS_ENUM_AVAILABLE_IOS(9.1) NS_SWIFT_NAME(iPadPro12_9Inch),
    JKHiOSDeviceiPadPro9_7Inch NS_ENUM_AVAILABLE_IOS(9.3) NS_SWIFT_NAME(iPadPro9_7Inch),
    JKHiOSDeviceiPad5 NS_ENUM_AVAILABLE_IOS(10.3) NS_SWIFT_NAME(iPad5),
    JKHiOSDeviceiPadPro12_9Inch2 NS_ENUM_AVAILABLE_IOS(10.3) NS_SWIFT_NAME(iPadPro12_9Inch2),
    JKHiOSDeviceiPadPro10_5Inch NS_ENUM_AVAILABLE_IOS(10.3) NS_SWIFT_NAME(iPadPro10_5Inch),
    JKHiOSDeviceiPad6 NS_ENUM_AVAILABLE_IOS(11.3) NS_SWIFT_NAME(iPad6),

    JKHiOSDeviceSimulator   NS_SWIFT_NAME(simulator),
    JKHiOSDeviceUnknown     NS_SWIFT_NAME(unknown)
} NS_SWIFT_NAME(iOSDevice);


NS_ASSUME_NONNULL_END
